name: space
description: A new Flutter project.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.9
  firebase_storage: ^10.2.8
  firebase_database: ^9.0.7
  image_picker: ^0.8.4+1
  geolocator: ^8.0.5
  geocoding: ^2.0.5
  geocoder2: ^1.4.0
  provider: ^6.0.4
  google_sign_in: ^5.1.0
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^5.0.0+4
  google_maps_flutter: ^2.0.9
  location: ^4.4.0
  dio: ^4.0.6
  google_fonts: ^2.3.0
  simple_animations: ^4.0.0
  page_transition: "^2.0.2"
  shared_preferences: ^2.0.7
  crypto: ^3.0.1
  flutter_svg: ^1.0.0
  #custom_navigator: ^0.3.0
  change_app_package_name: ^1.0.0
  flutter_login_facebook: ^1.7.0
  photo_view: ^0.14.0
  rsa_encrypt: ^2.0.0





















  


  sqflite: ^2.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/login_logo.png
    - assets/images/flutter1.png
    - assets/images/ok.png
    - assets/images/gallery.png
    - assets/images/camera.png
    - assets/images/google_login.png
    - assets/images/left.png
    - assets/images/up.png
    - assets/images/navigator.png
    - assets/images/ringing.png
    - assets/images/ringing1.png
    - assets/images/like.png
    - assets/images/user.png
    - assets/images/placeholder.png
    - assets/images/adres.png
    - assets/images/user22.png
    - assets/images/adres22.png
    - assets/images/placeholder22.png
    - assets/images/next.png
    - assets/images/rightt.png
    - assets/images/rightt2.png
    - assets/images/mail-inbox-app.png
    - assets/images/exit.png
    - assets/images/user22.svg
    - assets/images/userprofil.png
    - assets/images/userprofil2.png
    - assets/images/adres22.svg
    - assets/images/placeholder22.svg
    - assets/images/placeholder2.svg
    - assets/images/user2.svg
    - assets/images/adres2.svg
    - assets/images/focus.png
    - assets/images/face.png
    - assets/images/google-plus.png
    - assets/images/notification.png
    - assets/images/notification1.png
    - assets/images/menu.png  
    - assets/images/space-icon3.jpg
    - assets/images/check.png     
    - assets/images/harita-konum.png                  
    - assets/images/hakkimda/back-in-time.png
    - assets/images/hakkimda/mortarboard.png
    - assets/images/hakkimda/gender-symbols.png
    - assets/images/hakkimda/length.png
    - assets/images/hakkimda/suitcase.png
    - assets/images/hakkimda/youtube.png
    - assets/images/hakkimda/snapchat.png
    - assets/images/hakkimda/instagram.png
    - assets/images/hakkimda/twitter.png












































  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf  

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf 
        
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne/FredokaOne-Regular.ttf 
                
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Black.otf

    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo/Baloo-Regular.ttf   
        




  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
